import type { RepoItem } from "./types";

export const MOCK_REPOS: RepoItem[] = [
  {
    id: 1,
    name: "neural-forge",
    full_name: "openmlab/neural-forge",
    html_url: "https://github.com/openmlab/neural-forge",
    description:
      "A blazing-fast framework for training and deploying multimodal models on edge devices.",
    language: "Python",
    stargazers_count: 18420,
    forks_count: 2103,
    open_issues_count: 87,
    topics: ["machine-learning", "pytorch", "edge-ai"],
    owner: {
      login: "openmlab",
      avatar_url: "https://avatars.githubusercontent.com/u/10245193?v=4",
    },
    created_at: "2026-08-06T10:00:00Z",
    pushed_at: "2026-08-08T14:22:00Z",
  },
  {
    id: 2,
    name: "react-paper",
    full_name: "newsdev/react-paper",
    html_url: "https://github.com/newsdev/react-paper",
    description:
      "Typography-first React components inspired by classic broadsheet layouts.",
    language: "TypeScript",
    stargazers_count: 9210,
    forks_count: 640,
    open_issues_count: 34,
    topics: ["react", "typography", "design-system"],
    owner: {
      login: "newsdev",
      avatar_url: "https://avatars.githubusercontent.com/u/9919?v=4",
    },
    created_at: "2026-08-05T08:30:00Z",
    pushed_at: "2026-08-08T11:05:00Z",
  },
  {
    id: 3,
    name: "oxide-db",
    full_name: "rustaceans/oxide-db",
    html_url: "https://github.com/rustaceans/oxide-db",
    description:
      "Embedded OLTP engine written in Rust with MVCC and async I/O.",
    language: "Rust",
    stargazers_count: 7430,
    forks_count: 512,
    open_issues_count: 19,
    topics: ["database", "rust", "storage"],
    owner: {
      login: "rustaceans",
      avatar_url: "https://avatars.githubusercontent.com/u/5430905?v=4",
    },
    created_at: "2026-08-04T16:45:00Z",
    pushed_at: "2026-08-08T09:18:00Z",
  },
  {
    id: 4,
    name: "go-fleet",
    full_name: "cloudnative/go-fleet",
    html_url: "https://github.com/cloudnative/go-fleet",
    description: "Lightweight orchestrator for container fleets at the edge.",
    language: "Go",
    stargazers_count: 5180,
    forks_count: 401,
    open_issues_count: 42,
    topics: ["kubernetes", "go", "devops"],
    owner: {
      login: "cloudnative",
      avatar_url: "https://avatars.githubusercontent.com/u/1342004?v=4",
    },
    created_at: "2026-08-03T12:00:00Z",
    pushed_at: "2026-08-07T20:44:00Z",
  },
  {
    id: 5,
    name: "swift-lens",
    full_name: "ioslabs/swift-lens",
    html_url: "https://github.com/ioslabs/swift-lens",
    description: "Composable optics for SwiftUI state management.",
    language: "Swift",
    stargazers_count: 3890,
    forks_count: 288,
    open_issues_count: 11,
    topics: ["swift", "swiftui", "functional"],
    owner: {
      login: "ioslabs",
      avatar_url: "https://avatars.githubusercontent.com/u/10639145?v=4",
    },
    created_at: "2026-08-02T09:15:00Z",
    pushed_at: "2026-08-08T07:30:00Z",
  },
  {
    id: 6,
    name: "deno-pulse",
    full_name: "denoland/deno-pulse",
    html_url: "https://github.com/denoland/deno-pulse",
    description: "Real-time analytics pipeline runtime for Deno and Web APIs.",
    language: "JavaScript",
    stargazers_count: 2760,
    forks_count: 195,
    open_issues_count: 28,
    topics: ["deno", "streaming", "analytics"],
    owner: {
      login: "denoland",
      avatar_url: "https://avatars.githubusercontent.com/u/42048915?v=4",
    },
    created_at: "2026-08-01T18:20:00Z",
    pushed_at: "2026-08-08T06:12:00Z",
  },
  {
    id: 7,
    name: "torch-viz",
    full_name: "mlviz/torch-viz",
    html_url: "https://github.com/mlviz/torch-viz",
    description: "Interactive graph visualizer for PyTorch computation graphs.",
    language: "Python",
    stargazers_count: 4520,
    forks_count: 330,
    open_issues_count: 15,
    topics: ["pytorch", "visualization"],
    owner: {
      login: "mlviz",
      avatar_url: "https://avatars.githubusercontent.com/u/21003710?v=4",
    },
    created_at: "2026-07-30T11:00:00Z",
    pushed_at: "2026-08-07T15:00:00Z",
  },
];
